coverage:
  precision: 2
  round: down
  range: "75...100"
  status:
    project:
      default:
        # basic
        target: 85.0%
        threshold: 5%
        branches: 
          - main
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false
    patch:
      default:
        # basic
        target: 85.0%
        threshold: 5%
        branches: 
          - main
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false